### PR TITLE
CI for Windows

### PR DESCRIPTION
**Pull request by iakov**
* Initial CI for Windows via GHA with `make check` to run unit-tests
* Basic `clang-msvc` support
* Fixes for `msvc` and `mingw`
* Support for LTO (`CONFIG+=ltcg`) builds on all platforms
* Minor code improvements, including build scripts unification

### CODE REVIEW

**Comment by iakov** [comment]
More fixes from my repo. This is a small step towards Windows CI, that I already have done. But since there are lots of changes, I'll try to split to a few PRs.

**Comment by iakov** [comment]
I was able to move from my repo the essential part for Win CI without other significant changes, so PR was renamed.

**Comment by iakov** [comment]
Please, re-run the failed Ubuntu workflow. Maybe servers a back online.

**Review by mrbean-bremen — APPROVED** [review]
Nice work, thanks a lot! 
As usually, I will wait a bit before merging, to give others a chance to  have a look.

**Comment by iakov** [comment]
Just FYI: It is very dangerous to use MSVC-built Python with  mingwXXX Qt runtime because of C runtime incompatibilities. I've encountered problems, but simple fix saved me from crash. The problem in my case was in `FILE*` data structure. Also, compiler incompatibilities can cause even Python's internal data structures to have different representations in pre-compiled `pythonXY.dll` and `PythonQt-Qt5-PythonX.Y.dll`. Please, take this into account. Probably, the pure MSYS build should be added to CI and some checks and warnings should be added to `python.prf`. If this makes sense, an issue may be opened for this case.

**Comment by mrbean-bremen** [comment]
>  If this makes sense, an issue may be opened for this case.

It totally makes sense in my opinion - feel free to open an issue!

**Comment by jamesobutler** [comment]
Hi all! I’ve observed the recent development here in the PythonQt repo recently which is great to see 🙏🏻. Are you all associated with MeVisLab? Are you all prepping the testing infrastructure and modernizing the build infrastructure with the specific next step of updating to Qt6 re https://github.com/MeVisLab/pythonqt/issues/13#issuecomment-1419390865?

**Comment by iakov** [comment]
I'm not associated with the MeVisLab. Just a responsible user of the PythonQt.

**Comment by usiems** [comment]
> Hi all! I’ve observed the recent development here in the PythonQt repo recently which is great to see 🙏🏻. Are you all associated with MeVisLab? Are you all prepping the testing infrastructure and modernizing the build infrastructure with the specific next step of updating to Qt6 re [#13 (comment)](https://github.com/MeVisLab/pythonqt/issues/13#issuecomment-1419390865)?

Me and @mrbean-bremen are members of the MeVisLab core developer team. And no, this is no direct preparation for Qt6 support - which is on our list, but not yet a pressing concern for us. It is just that my colleague got fed up with the current situation of neglect enough to do something about it. Many thanks for that! Obviously it inspired others to help out, too, which we are also thankful for.

**Pull request merged**
