### PR TITLE
Add back undefining _POSIX_C_SOURCE and _XOPEN_SOURCE

### PR DESCRIPTION
**Pull request by mrbean-bremen**
- only undefining _POSIX_THREADS had be a problem
- see #103

### CODE REVIEW

**Comment by he-hesce** [comment]
I think it's good!

**Comment by he-hesce** [comment]
Gold star release!

**Comment by mrbean-bremen** [comment]
Thanks, good to know!

**Comment by he-hesce** [comment]
@mrbean-bremen: Although RHEL/CentOS 7 is our in-house platform and will slowly be moved to RHEL/Rocky 9 over the coming years. We skipped RHEL/Rocky 8 as it was just a possible upgrade path while waiting for 9. Ubuntu is just a backup platform in case RHEL/Rocky/AlmaLinux go (more than today) bonkers and we need a way out away from them - not that Ubuntu isn't bonkers themselves.

**Pull request merged**
