### PR TITLE
Force C++11 for older Qt versions with obsolete compilers (f.e. GCC 4.9.2)

### PR DESCRIPTION
**Pull request by iakov**
+ small fix for rare problem, but this reference management pattern is safer and preferable

### CODE REVIEW

**Review by mrbean-bremen — APPROVED** [review]

**Comment by iakov** [comment]
Any objections? Or can be merged? ;)

**Comment by mrbean-bremen** [comment]
@usiems - can you have a look?

**Comment by usiems** [comment]
Not sure if this might introduce problems down the line if Qt requires a greater C++ version than 11, but I guess we can fix that if problems arise.

**Review by usiems — APPROVED** [review]

**Comment by iakov** [comment]
There is another problem with Qt6 that requires C++17. Even the generator project fails to compile with GCC 13 if `-ansi -pedantic -Werror` are in effect.  This is caused by Qt6 mkspecs.... Explicit `CONFIG+=c++14` does not influence command-line parameters. Only `CONFIG+=c++17` helps. As a compromise, the `CONFIG+=c++latest` can be used to be safe (as compatible with older compilers). But that is another story...

**Pull request merged**
